[package]
name = "tapasco"
version = "1.0.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[lib]
crate-type = ["staticlib", "rlib"]

[profile.release]
opt-level = 3
codegen-units = 1
lto = "fat"

[dependencies]
log = "0.4.8"
chrono = "0.4.11"
nix = "0.17.0"
memmap = "0.7.0"
getset = "0.1.0"
snafu = "0.6.6"
prost = "0.6.1"
env_logger = "0.7.1"
lockfree = "0.5.1"
crossbeam = "0.7.3"
volatile = "0.2.6"
bytes = "0.5.4"
libc = "0.2.70"
config = "0.10.1"
serde = "1.0.115"
vfio-bindings = "0.2.0"

[build-dependencies]
prost-build = "0.6.1"
cbindgen = "0.14.2"
